In [1]:
import pandas as pd
import numpy as np
import math
import sqlite3
from sklearn.decomposition import NMF


In [2]:
db = sqlite3.connect('../database/ML_latsmall.db')
db

In [3]:
#def q(query):
#    return pd.read_sql(query, db)

In [4]:
#q("SELECT * FROM ml_ratings LIMIT 10")

In [5]:
query = 'SELECT movieId, userId, rating FROM ml_ratings'
df = pd.read_sql(query, db)
df.head(10)

movieId  userId  rating
0        1       1     4.0
1        3       1     4.0
2        6       1     4.0
3       47       1     5.0
4       50       1     5.0
5       70       1     3.0
6      101       1     5.0
7      110       1     4.0
8      151       1     5.0
9      157       1     5.0

In [6]:
#df.sort_values(by=['userId', 'movieId'], inplace=True)

In [7]:
long = df.groupby(['userId', 'movieId'])['rating'].mean()
long.head()

userId  movieId
1       1          4.0
        3          4.0
        6          4.0
        47         5.0
        50         5.0
Name: rating, dtype: float64

In [8]:
wide = long.unstack()

In [9]:
wide = wide.fillna(0.0)
wide.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 610 entries, 1 to 610
Columns: 9724 entries, 1 to 193609
dtypes: float64(9724)
memory usage: 45.3 MB


In [10]:
R = wide
R

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           4.0     0.0     4.0     0.0     0.0     4.0     0.0     0.0   
2           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5           4.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
6           0.0     4.0     5.0     3.0     5.0     4.0     4.0     3.0   
7           4.5     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
8           0.0     4.0     0.0     0.0     0.0     0.0     0.0     0.0   
9           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
10          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
11          0.0     0.0     0.0     0.0     0.0     5.0     0.0     0.0   
12          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
13          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
14          0.0     0.0     0.0     3.0     0.0     0.0     3.0     0.0   
15          2.5     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
16          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
17          4.5     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
18          3.5     3.0     0.0     0.0     0.0     4.0     0.0     0.0   
19          4.0     3.0     3.0     0.0     0.0     0.0     2.0     0.0   
20          0.0     3.0     0.0     0.0     0.0     0.0     0.0     1.0   
21          3.5     3.5     0.0     0.0     0.0     0.0     0.0     0.0   
22          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
23          0.0     0.0     0.0     0.0     0.0     4.0     0.0     0.0   
24          0.0     0.0     0.0     0.0     0.0     4.5     0.0     0.0   
25          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
26          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
27          3.0     4.0     0.0     0.0     0.0     0.0     0.0     0.0   
28          0.0     0.0     0.0     0.0     0.0     3.5     0.0     0.0   
29          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
30          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...         ...     ...     ...     ...     ...     ...     ...     ...   
581         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
582         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
583         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
584         5.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
585         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
586         0.0     4.0     0.0     0.0     0.0     0.0     0.0     0.0   
587         5.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
588         0.0     0.0     3.0     0.0     0.0     5.0     0.0     0.0   
589         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
590         4.0     2.5     3.0     0.0     2.0     3.5     0.0     0.0   
591         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
592         0.0     4.0     0.0     0.0     0.0     3.0     0.0     0.0   
593         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
594         0.0     4.0     4.0     0.0     0.0     0.0     0.0     0.0   
595         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
596         4.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
597         4.0     0.0     0.0     0.0     0.0     3.0     1.0     0.0   
598         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
599         3.0     2.5     1.5     0.0     0.0     4.5     2.5     0.0   
600         2.5     4.0     0.0     1.5     2.5     0.0     3.5     0.0   
601         4.0     0.0  

In [30]:
index = userId

NameError: name 'userId' is not defined

In [29]:
R.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 610 entries, 1 to 610
Columns: 9724 entries, 1 to 193609
dtypes: float64(9724)
memory usage: 45.3 MB


In [ ]:
R.m

In [11]:
# model assumes R ~ PQ'
model = NMF(n_components=2, init='random')
model.fit(R)

NMF(alpha=0.0, beta_loss='frobenius', init='random', l1_ratio=0.0,
  max_iter=200, n_components=2, random_state=None, shuffle=False,
  solver='cd', tol=0.0001, verbose=0)

In [12]:
P = model.components_  # movie feature
P

array([[1.6687928 , 1.17778002, 0.        , ..., 0.00822844, 0.00822844,
        0.0266941 ],
       [2.53161801, 1.13251541, 0.93728278, ..., 0.        , 0.        ,
        0.        ]])

In [13]:
Q = model.transform(R)  # user feature
Q

array([[0.04418549, 0.94008617],
       [0.13416234, 0.        ],
       [0.        , 0.02590871],
       ...,
       [0.90661108, 1.11658021],
       [0.        , 0.14567472],
       [2.41871752, 0.03068528]])

In [14]:
# Value of the Loss Fuction
model.reconstruction_err_

1004.8718573383243

In [15]:
Q.shape, P.shape

((610, 2), (2, 9724))

In [16]:
nR = np.dot(Q, P)
nR

array([[2.45367551e+00, 1.11670287e+00, 8.81126578e-01, ...,
        3.63577789e-04, 3.63577789e-04, 1.17949193e-03],
       [2.23889140e-01, 1.58013718e-01, 0.00000000e+00, ...,
        1.10394703e-03, 1.10394703e-03, 3.58134258e-03],
       [6.55909636e-02, 2.93420164e-02, 2.42837902e-02, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [4.33970060e+00, 2.33233270e+00, 1.04655140e+00, ...,
        7.45999689e-03, 7.45999689e-03, 2.42011653e-02],
       [3.68792746e-01, 1.64978866e-01, 1.36538407e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.11402179e+00, 2.88346871e+00, 2.87607855e-02, ...,
        1.99022774e-02, 1.99022774e-02, 6.45654833e-02]])

In [17]:
nR.T

array([[2.45367551e+00, 2.23889140e-01, 6.55909636e-02, ...,
        4.33970060e+00, 3.68792746e-01, 4.11402179e+00],
       [1.11670287e+00, 1.58013718e-01, 2.93420164e-02, ...,
        2.33233270e+00, 1.64978866e-01, 2.88346871e+00],
       [8.81126578e-01, 0.00000000e+00, 2.42837902e-02, ...,
        1.04655140e+00, 1.36538407e-01, 2.87607855e-02],
       ...,
       [3.63577789e-04, 1.10394703e-03, 0.00000000e+00, ...,
        7.45999689e-03, 0.00000000e+00, 1.99022774e-02],
       [3.63577789e-04, 1.10394703e-03, 0.00000000e+00, ...,
        7.45999689e-03, 0.00000000e+00, 1.99022774e-02],
       [1.17949193e-03, 3.58134258e-03, 0.00000000e+00, ...,
        2.42011653e-02, 0.00000000e+00, 6.45654833e-02]])

In [18]:
# Query A with 5 movies (scifi) at 5 stars
a = np.zeros(9724)
a[[260, 1196, 1210, 2628, 5378]] = 5.0
a = a.reshape((1, -1))

In [19]:
t = model.transform(a)

In [20]:
t.shape

(1, 2)

In [21]:
res = np.dot(t, P)

In [22]:
res.shape

(1, 9724)

In [36]:
d = dict(zip(R.columns, res[0]))

In [39]:
import operator
sorted_d = sorted(d.items(), key=operator.itemgetter(1), reverse=True)
sorted_d

[(296, 0.05651431437454346),
 (593, 0.05517144031448565),
 (356, 0.05075176084381479),
 (480, 0.049361039990869285),
 (260, 0.04903955721194213),
 (457, 0.048926698901193194),
 (110, 0.04803657308594763),
 (589, 0.04780754939896299),
 (318, 0.046333328690709455),
 (1196, 0.04588333623314202),
 (608, 0.04528185842199142),
 (592, 0.04290838648778545),
 (527, 0.0417385042938826),
 (590, 0.04170584504890283),
 (50, 0.041571741626493686),
 (1210, 0.04152899385669013),
 (32, 0.04138865834689182),
 (150, 0.040661694277585085),
 (858, 0.04064448096695255),
 (1198, 0.040398026680955344),
 (1, 0.04022723280461297),
 (1197, 0.04009352571538493),
 (2858, 0.04000652858154818),
 (380, 0.0390512921850851),
 (2571, 0.037893248739086005),
 (1136, 0.0374585990555261),
 (1214, 0.03723991341841299),
 (1097, 0.03654927547652819),
 (2028, 0.03639845033796753),
 (1270, 0.03616999126143341),
 (1265, 0.03611537143268288),
 (1208, 0.03562411980156498),
 (1240, 0.03562383569477794),
 (47, 0.03557722837345735),
 